### PR TITLE
Server Info Page and Player Kick function

### PR DESCRIPTION
**Pull request by alexfriesen**
I added a dropdown with a kick player button in the playerlist
kick

### CODE REVIEW

**Comment by alexfriesen** [comment]
I  also added a Server Info Page which will be opened after the user connected to a server
server

**Comment by warik-zp** [comment]
This query function or console?
I have this information: https://imgur.com/LUEssx6
I need "Uptime", "Game time" and "Framerate".

**Comment by alexfriesen** [comment]
I'm sending the command "serverinfo" which returns a JSON with all the juicy information

**Comment by warik-zp** [comment]
Thank you for answer.

**Comment by garrynewman** [comment]
Nice, thanks

**Pull request merged**
